<?php
function load_frontend_enqueue()
{
    if (constant("IS_VIRTUAL_ENV")) {
        /**
         *  Since this is a virtual ENV 
         *  should only add wp_enqueue_script since styles are added via javascript! :)
         *  @author: Andres
         */

        $enqueueDev = 'virtual';
        wp_enqueue_script($enqueueDev . '-project', 'http://localhost:9000/virtual.project.js', [], '', true);

    } else {

        $enqueueProd = 'static';
        $defer = 'defer';

        /**
         *  tf_common_styles CSS 
         *  Generated by webpack based on cacheGroups / styles ( webpack.prod)
         *  @author: Andres
         */

        wp_enqueue_style($enqueueProd . '-project', get_stylesheet_directory_uri() . '/dist/css/project.' . constant("enqueue-hash") . '.css', [], null);
        wp_enqueue_script($enqueueProd . '-project-' . $defer, get_template_directory_uri() . '/dist/js/project.' . constant("enqueue-hash") . '.js', [], null, true);

    }
}
add_action('wp_enqueue_scripts', 'load_frontend_enqueue', 100);